config/routes.rb
BarterRaleigh::Application.routes.draw do

  

  resources :contact_forms
  get "contact_form/new"
  get "contact_form/create"

  devise_for :users
  get "welcome/index"

  get "pages/about"

  get "pages/post_creation"
  
  get "pages/edit_profile"

  get "pages/marketplace"

  get "pages/help"

  root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  def new
  	@contact_form = ContactForm.new
  end

  def create
  	begin
  		@contact_form = ContactForm.new
  		@contact_form.request = request
  		if @contact_form.deliver
  			flash.now[:notice] = 'Thank you for the message!'
  		else
  			render :new
  		end
  	rescue ScriptError
  		flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
  	end
  end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController

  def index
    head :ok
  end

  def show
    head :ok

  end

  def new
  	@contact_form = ContactForm.new
  end

  def create
  	begin
  		@contact_form = ContactForm.new
  		@contact_form.request = request
  		if @contact_form.deliver
  			flash.now[:notice] = 'Thank you for the message!'
  		else
  			render :new
  		end
  	rescue ScriptError
  		flash[:error] = 'Sorry, this message appears to be spam and was not delivered.'
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def post_creation
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/messages_controller_helper.rb
module MessagesControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact_form/create.html.erb
<h1>ContactForm#create</h1>

<h1>Thank you for your message.</h1>
<p>We'll get back to you as soon as possible.</p>
<p>
  <%= link_to 'Home', root_url, :class => 'button' %>
</p>

app/views/contact_form/new.html.erb
<h1>ContactForm#new</h1>

<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name, :required => false %>
  <%= f.input :email, :required => false %>
  <%= f.input :message, :as => :text, :required => false %>
  <div class="hidden">
    <%= f.input :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <%= f.button :submit, 'Send message' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BarterRaleigh" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="../welcome/index">BarterRaleigh</a>
          <div class="float_right">
            <ul class="nav">
              <li><%= link_to "Contact", contact_forms_path  %></li>
              <li><%= link_to "About", "../pages/about"  %></li>
              <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>
            
    <br>
    <br>
    <br>
    <footer>
      <p>&copy; Company 2014</p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>What can you tell me about Barter Raleigh's whereabouts?</h1>


<p>The quick brown fox jumped over the fence.</p>

app/views/pages/edit_profile.html.erb
<h1>Edit your profile here.</h1>
<br>
<br>
<p>Time to add some forms!</p>
<br>
<a href="../pages/post_creation">Back</a>

app/views/pages/help.html.erb
<h1>Help!  I need somebody...</h1>

<br>

<h2>Help! Not just anybody...</h2>

<br>

<p>Find me in app/views/pages/help.html.erb</p>

<br>
<a href="../pages/post_creation">Back</a>

app/views/pages/marketplace.html.erb
<h1>You have made it to the market!</h1>


<br>

<h3>Let's make a deal!</h3>

<br>

<p>Find me in app/views/pages/marketplace.html.erb</p>

<br>

<a href="../pages/post_creation">Back</a>

app/views/pages/post_creation.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
	
	<body>
		<h1 class="welcome">Welcome to Barter Raleigh, {name}!</h1>


		<h3 class="option">Here are a few options to get you going.</h3>

		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<p class="link"><a href="../pages/edit_profile">Edit Profile</a></p> 
					<p class="text">Use this link to make changes to your profile.  Make it easy for us to get to know you, we can become friends :)</p>
				</div>

				<div class="col-md-4">
					<p class="link"><a href="../pages/marketplace">Start Trading</a></p>
					<p class="text">If you are the kind of person who likes to skip the intro and get right into the thick of things, then by all means head into the marketplace and start trading now!</p>
				</div>

				<div class="col-md-4">
					<p class="link"><a href="../pages/help">Get Help</a></p>
					<p class="text">Feel like you are trying to navigate the Water Temple without a good map?  Our support team will get you back on track in no time!</p>
				</div>
			</div>
		</div>

        <script src="http://code.jquery.com/jquery.js"></script>
    	<script src="js/bootstrap.min.js"></script>
	</body>

</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Barter Raleigh</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
	
	<body>
		<h1>Hello, and welcome to the Barter Raleigh App!</h1>
	</body>















</html>